version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
